version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./.data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: clean-node-api
    image: node:20
    user: node
    command: bash -c "npm install && npm run debug"
    working_dir: /app
    restart: always
    volumes:
      - .:/app
    ports:
      - '5050:5050'
      - '9222:9222'
    depends_on:
      - mongo
