name: CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build:ci

name: Publish to coveralls.io
uses: coverallsapp/github-action@master
with:
  github-token: ${{ secrets.GITHUB_TOKEN }}
  path-to-lcov: ./coverage/lcov.info
  
